config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :registrations => 'admins/registrations',
    :sessions => 'admins/sessions',
    :passwords => 'admins/passwords'
  }

  devise_for :users, :controllers => {
  	:registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admins do
    resources :users
    resources :questions
    resources :articles
    resources :programming_languages
    resources :companies do
      resources :evaluations
    end
  end

  root to: "users/top#top"

  namespace :users do
  	get "users/search" => "users#search"
  	put "questions/:id" => "questions#best_answer"

  	resources :users
    get "questions/genre/:id" => "questions#genre_index", as: "questions_genre"
  	resources :questions do
  		resources :answers, only: [:create, :destroy] do
  			resource :favorites, only: [:create, :destroy]
  		end
  		post "favorites" => "favorites#question_favorite_create", as: "favorites"
      delete "favorites" => "favorites#question_favorite_destroy"
  	end

  	resources :articles do
  		post "favorites" => "favorites#article_favorite_create", as: "favorites"
      delete "favorites" => "favorites#article_favorite_destroy"
      resources :post_comments, only: [:create, :destroy]
  	end

  	resources :relationships, only: [:create, :destroy]
  	resources :post_images

  	resources :companies do
	  	resources :evaluations do
	  		collection do
	  			get :next
	  			post :next
	  		end
	  	end
	  end

  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :user
	belongs_to :question
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	validates :answer, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :post_comments, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	validates :article_title, :article_body, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :evaluations, dependent: :destroy

	enum is_listing: { 上場:true, 非上場:false }

	validates :company_name, :main_office, :ceo, :foundation_date, :is_listing, presence: true
end

app/models/company_valuation.rb
class CompanyValuation < ApplicationRecord
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
	belongs_to :company
	belongs_to :user

	enum employment_type: { 正社員:0, 契約社員:1, 派遣社員:2 }
	enum generation: { "20代":0, "30代":1, "40代":2, "50代":3, "60代":4 }
	enum gender: { 男性:0, 女性:1 }
	enum is_enrollment: { 在籍中:true, 退社済:false }
	enum enrollment_period: { "3年未満":0 ,"3年〜10年未満":1, "10年以上":2 }

	validates :working_time, :rewarding, :communication, :holiday, :salary, :growth_environment, numericality: {
		less_than_or_equal_to: 5,
		greater_than_or_equal_to: 1
	}, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :question, optional: true
	belongs_to :answer, optional: true
	belongs_to :article, optional: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :article

	validates :comment, presence: true
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
	attachment :image
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
	has_many :questions, dependent: :destroy
	enum is_enabled: { 有効: true, 無効: false }
end

app/models/question.rb
class Question < ApplicationRecord

	belongs_to :user
	belongs_to :programming_language
	has_many :answers, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	validates :question_title, :question_body, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: "User"

	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :answers
  has_many :post_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follow_id"
  has_many :followers, through: :reverse_of_relationships, source: :user

  attachment :profile_image

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  enum prefecture: {
    "--未選択--":0,北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

  enum gender: {
    問わない:0,男性:1,女性:2
  }

  acts_as_paranoid

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :birthday, :gender, :postcode, :prefecture, :address, :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
		case resource
      when User
        root_path
      when Admin
        admins_questions_path
      end
    end
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,
														   :first_name,
														   :last_name_kana,
														   :first_name_kana,
														   :birthday,
														   :gender,
														   :postcode,
														   :prefecture,
														   :address,
														   :phone_number])
	end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users/top_helper.rb
module Users::TopHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/_list.html.erb
<div class="btn-group d-flex">
	<%= link_to "Q＆A一覧", admins_questions_path, class: "btn page-link text-dark d-inline-block w-100" %>
	<%= link_to "記事一覧", admins_articles_path, class: "btn page-link text-dark d-inline-block w-100" %>
	<%= link_to "言語ジャンル", admins_programming_languages_path, class: "btn page-link text-dark d-inline-block w-100" %>
	<%= link_to "ユーザー一覧", admins_users_path, class: "btn page-link text-dark d-inline-block w-100" %>
	<%= link_to "企業評価一覧", admins_companies_path, class: "btn page-link text-dark d-inline-block w-100" %>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>