config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :registrations => 'admins/registrations',
    :sessions => 'admins/sessions',
    :passwords => 'admins/passwords'
  }

  devise_for :users, :controllers => {
  	:registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admins do
    resources :users
    resources :questions
    resources :articles
    resources :programming_languages
    resources :companies do
      resources :evaluations
    end
  end

  root to: "users/top#top"

  namespace :users do
  	get "users/search" => "users#search"
  	put "questions/:id" => "questions#best_answer"

  	resources :users
    get "questions/genre/:id" => "questions#genre_index", as: "questions_genre"
  	resources :questions do
  		resources :answers, only: [:create, :destroy] do
  			resource :favorites, only: [:create, :destroy]
  		end
  		post "favorites" => "favorites#question_favorite_create", as: "favorites"
      delete "favorites" => "favorites#question_favorite_destroy"
  	end

  	resources :articles do
  		post "favorites" => "favorites#article_favorite_create", as: "favorites"
      delete "favorites" => "favorites#article_favorite_destroy"
      resources :post_comments, only: [:create, :destroy]
  	end

  	resources :relationships, only: [:create, :destroy]
  	resources :post_images

  	resources :companies do
	  	resources :evaluations do
	  		collection do
	  			get :next
	  			post :next
	  		end
	  	end
	  end

  end
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :evaluations, dependent: :destroy

	enum is_listing: { 上場:true, 非上場:false }

	validates :company_name, :main_office, :ceo, :foundation_date, :is_listing, presence: true
end

app/controllers/admins/companies_controller.rb
class Admins::CompaniesController < ApplicationController
	def index
		@q = Company.ransack(params[:q])
		@companies = @q.result(distinct: true).order(created_at: :"DESC").page(params[:page])
	end

	def edit
		@company = Company.find(params[:id])
	end

	def update
		@company = Company.find(params[:id])
		@company.update(company_params)
		redirect_to admins_companies_path
	end

	def destroy
		company = Company.find(params[:id])
		company.destroy
		redirect_to admins_companies_path
	end

	private
	def company_params
		params.require(:company).permit(:company_name, :main_office, :ceo, :employee_number, :foundation_date, :is_listing, :hp)
	end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
	def index
		@q = User.with_deleted.ransack(params[:q])
		@users = @q.result(distinct: true).order(created_at: :"DESC").page(params[:page])
	end
	def destroy
		user = User.find(params[:id])
		user.destroy
		redirect_to admins_users_path
	end

	private
	def user_params
		params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :birthday, :gender, :postcode, :prefecture, :address, :phone_number, :profile_image)
	end
end

app/controllers/users/answers_controller.rb
class Users::AnswersController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@question = Question.find(params[:question_id])
		@answer = current_user.answers.new(answer_params)
		@answer.question_id = @question.id
		if @answer.save
			redirect_to users_question_path(@question)
		else
			render template: "users/questions/show"
		end
	end

	private
	def answer_params
		params.require(:answer).permit(:answer)
	end
end

app/controllers/users/articles_controller.rb
class Users::ArticlesController < ApplicationController
	before_action :authenticate_user!
	
	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.user_id = current_user.id
		if @article.save
			redirect_to users_article_path(@article)
		else
			render :new
		end
	end

	def index
		@articles = Article.page(params[:page])
	end

	def show
		@article = Article.find(params[:id])
		@post_comment = PostComment.new
	end

	def edit
		@article = Article.find(params[:id])
		if @article.user != current_user
			redirect_to users_article_path(@article)
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to users_article_path(@article)
		else
			render :edit
		end
	end

	private
	def article_params
		params.require(:article).permit(:user_id, :article_title, :article_body)
	end
end

app/controllers/users/companies_controller.rb
class Users::CompaniesController < ApplicationController
	before_action :authenticate_user!

	def index
		@q = Company.ransack(params[:q])
		@companies = @q.result(distinct: true).order(created_at: :"DESC").page(params[:page])
	end

	def show
		@company = Company.find(params[:id])
	end

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(company_params)
		if @company.save
			redirect_to users_companies_path
		else
			render :new
		end
	end

	private
	def company_params
		params.require(:company).permit(:company_name, :main_office, :ceo, :employee_number, :foundation_date, :is_listing, :hp)
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/evaluations_controller.rb
class Users::EvaluationsController < ApplicationController
	before_action :authenticate_user!
	
	def new
		@evaluation = Evaluation.new
	end

	def next
		session[:working_time] = evaluation_params[:working_time].to_f
		session[:rewarding] = evaluation_params[:rewarding].to_f
		session[:communication] = evaluation_params[:communication].to_f
		session[:holiday] = evaluation_params[:holiday].to_f
		session[:salary] = evaluation_params[:salary].to_f
		session[:growth_environment] = evaluation_params[:growth_environment].to_f
		@evaluation = Evaluation.new
	end

	def create
		evaluation = Evaluation.new(
			working_time: session[:working_time],
			rewarding: session[:rewarding],
			communication: session[:communication],
			holiday: session[:holiday],
			salary: session[:salary],
			growth_environment: session[:growth_environment],
			average: (session[:working_time] + session[:rewarding] + session[:communication] + session[:holiday] + session[:salary] + session[:growth_environment]) / 6,
			employment_type: evaluation_params[:employment_type],
			generation: evaluation_params[:generation].to_i,
			gender: evaluation_params[:gender],
			enrollment_period: evaluation_params[:enrollment_period].to_i,
			is_enrollment: evaluation_params[:is_enrollment],
			annual_income: evaluation_params[:annual_income],
			review: evaluation_params[:review]
			)
		company = Company.find(params[:company_id])
		evaluation.user_id = current_user.id
		evaluation.company_id = company.id
		evaluation.score = Language.get_data(evaluation_params[:review])
		evaluation.save
		redirect_to users_companies_path
	end

	def show
		@evaluation = Evaluation.find(params[:id])
	end


	private
	def evaluation_params
		params.require(:evaluation).permit(:user_id, :company_id, :average, :working_time, :rewarding, :communication, :holiday, :salary, :growth_environment, :employment_type, :generation, :gender, :enrollment_period, :is_enrollment, :annual_income, :review)
	end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController

	def question_favorite_create
		@question = Question.find(params[:question_id])
		favorite = current_user.favorites.new(question_id: @question.id)
		favorite.save
	end

	def question_favorite_destroy
		@question = Question.find(params[:question_id])
		favorite = current_user.favorites.find_by(question_id: @question.id)
		favorite.destroy
	end

	def article_favorite_create
		@article = Article.find(params[:article_id])
		favorite = current_user.favorites.new(article_id: @article.id)
		favorite.save 
	end

	def article_favorite_destroy
		@article = Article.find(params[:article_id])
		favorite = current_user.favorites.find_by(article_id: @article.id)
		favorite.destroy
	end

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/post_comments_controller.rb
class Users::PostCommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@article = Article.find(params[:article_id])
		@post_comment = current_user.post_comments.new(post_comment_params)
		@post_comment.article_id = @article.id
		if @post_comment.save
			redirect_to users_article_path(@article)
		else
			render template: "users/articles/show"
		end
	end

	private
	def post_comment_params
		params.require(:post_comment).permit(:comment)
	end

end

app/controllers/users/post_images_controller.rb
class Users::PostImagesController < ApplicationController
	def create
		@post_image = PostImage.new(post_image_params)
		@post_image.user_id = current_user.id
		@post_image.save
		redirect_to users_user_path(current_user.id)
	end
	private
	def post_image_params
		params.require(:post_image).permit(:image)
	end
end

app/controllers/users/questions_controller.rb
class Users::QuestionsController < ApplicationController
	before_action :authenticate_user!

	def new
		@question = Question.new
	end

	def create
		@question = Question.new(question_params)
		@question.user_id = current_user.id
		if @question.save
			redirect_to users_question_path(@question)
		else
			render :new
		end
	end

	def edit
		@question = Question.find(params[:id])
		if @question.user != current_user
			redirect_to users_question_path(@question)
		end
	end

	def update
		@question = Question.find(params[:id])
		if @question.update(question_params)
			redirect_to users_question_path(@question)
		else
			render :edit
		end
	end

	def best_answer
		@question = Question.find(params[:id])
		@question.best_answer_id = params[:best_answer_id]
		if @question.save
			redirect_to users_question_path(@question)
		else
			render :show
		end
	end

	def index
		@q = Question.ransack(params[:q])
		@questions = @q.result(distinct: true).where(best_answer_id: nil).page(params[:question_page]).order(id: :DESC)
		@solved_questions = @q.result(distinct: true).where.not(best_answer_id: nil).page(params[:solved_question_page]).order(id: :DESC)
		@programming_languages = ProgrammingLanguage.all
	end

	def genre_index
		@programming_languages = ProgrammingLanguage.all
		@programming_language = ProgrammingLanguage.find(params[:id])
		@q = Question.ransack(params[:q])
		@questions = @q.result(distinct: true).where(programming_language_id: @programming_language, best_answer_id: nil).page(params[:question_page]).order(id: :DESC)
		@solved_questions = @q.result(distinct: true).where(programming_language_id: @programming_language).where.not(best_answer_id: nil).page(params[:solved_question_page]).order(id: :DESC)
	end

	def show
		@question = Question.find(params[:id])
		@answer = Answer.new
	end

	private
	def question_params
		params.require(:question).permit(:user_id, :question_title, :question_body, :programming_language_id, :best_answer_id)
	end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
	before_action :set_user

      def create
        following = current_user.follow(@user)
        following.save
      end

      def destroy
        following = current_user.unfollow(@user)
        following.destroy
      end

      def following
        @user = User.find(params[:id])
        @users = @user.followings
        redirect_back(fallback_location: root_path)
      end

      def followers
        @user = User.find(params[:id])
        @users = @user.followers
        redirect_back(fallback_location: root_path)
      end

      private
      def set_user
        @user = User.find(params[:id])
      end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def new_guest
    user = User.find(1)
    user.update(email: 'guest@example.com',
                last_name: 'ゲスト',
                first_name: 'ユーザー',
                last_name_kana: 'ゲスト',
                first_name_kana: 'ユーザー',
                birthday: '2020-1-1',
                gender: '男性',
                postcode: '1112222',
                prefecture: '東京都',
                address: '千代田区',
                phone_number: '00000000000') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in user
    redirect_to root_path
  end

end

app/controllers/users/top_controller.rb
class Users::TopController < ApplicationController
	before_action :authenticate_user!

	def top
		@questions = Question.where(best_answer_id: nil).order(created_at: :"DESC")
		@users = User.where.not(id: current_user.id).order(created_at: :"DESC")
	end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/companies/index.html.erb
<div class="container">
	<%= render "users/top/list" %>

	<%= search_form_for @q, url: users_companies_path do |f| %>
		<div class="row mt-5">
			<div class="col-5 offset-3"><%= f.search_field :company_name_cont, class: "form-control" %></div>
			<div class="col-1"><%= f.submit "検索", class: "btn btn-primary btn-block" %></div>
		</div>
	<% end %>

	<div class="row">
		<div class="col-5 offset-3"><%= link_to "=>企業が見つからない場合は企業情報を入力して下さい", new_users_company_path %></div>
	</div>

	<div class="row">
		<div class="col mt-5">
			<table class="table">
				<% @companies.each do |company| %>
					<tr>
						<td class="align-middle border-bottom" width="200"><%= company.company_name %></td>
						<% if company.evaluations.count != 0 %>
							<td class="align-middle border-bottom" width="200"><div id="star-rate-<%= company.id %>"></div></td>
						<% else %>
							<td class="align-middle border-bottom" width="200"><div id="star-rate-<%= company.id %>"></div></td>
						<% end %>
							<td class="align-middle border-bottom" width="150">クチコミ数：<%= company.evaluations.count %></td>
							<td class="align-middle border-bottom" width="150"><%= link_to "詳細を見る", users_company_path(company) %></td>
					</tr>
					<script>
		        	$('#star-rate-<%= company.id %>').raty({
               	  	size: 36,
                  	starOff: '<%= asset_path("star-off.png") %>',
                  	starOn : '<%= asset_path("star-on.png") %>',
                  	starHalf: '<%= asset_path("star-half.png") %>',
                  	half: true,
                  	readOnly: true,
                  	score: <%= company.evaluations.count == 0 ? 0 : company.evaluations.pluck(:average).sum / company.evaluations.count %>,
                	});
					</script>
				<% end %>
			</table>
		</div>
	</div>
	<div class="col-4 offset-4"><%= paginate @companies %></div>
</div>

app/views/users/companies/new.html.erb
<%= form_with model: @company, url: users_companies_path, local: true do |f| %>
<div class="container">
	<%= render 'layouts/error_messages', model: f.object %>
	<div class="col-2 offset-1 h4">企業情報入力</div>

	 <div class="row mt-5">
	 	<div class="col-3"><span class="align-middle">企業名</span></div>
	 	<div class="col-3"><%= f.text_field :company_name, autofocus: true, class: "form-control" %></div>
	 </div>

	 <div class="row mt-3">
	 	<div class="col-3"><span class="align-middle">本社所在地</span></div>
	 	<div class="col-6"><%= f.text_field :main_office, autofocus: true, class: "form-control" %></div>
	 </div>

	 <div class="row mt-3">
	 	<div class="col-3"><span class="align-middle">代表者名</span></div>
	 	<div class="col-3"><%= f.text_field :ceo, autofocus: true, class: "form-control" %></div>
	 </div>

	 <div class="row mt-3">
	 	<div class="col-3"><span class="align-middle">従業員数</span></div>
	 	<div class="col-3"><%= f.text_field :employee_number, autofocus: true, class: "form-control" %></div>
	 	<div class="col-1 d-flex align-items-center">人</div>
	 </div>

	 <div class="row mt-3">
	    <div class="col-3"><span class="align-middle">設立年月</span></div>
	    <div class="col-3"><%= raw sprintf(f.date_select(:foundation_date, use_month_numbers: true, discard_day: true, start_year: 1930, end_year: (Time.now.year), default: Date.new(1989, 1), date_separator: '%s'),'年 ') +'月 ' %></div>
  	</div>

  	<div class="row mt-3">
	    <div class="col-3"><span class="align-middle">上場区分</span></div>
	    <div class="col-3"><%= f.radio_button :is_listing, :上場 %> <%= f.label :上場 %> <%= f.radio_button :is_listing, :非上場 %> <%= f.label :非上場 %></div>
	</div>

	<div class="row mt-3">
	 	<div class="col-3"><span class="align-middle">HPのURL</span></div>
	 	<div class="col-6"><%= f.text_field :hp, autofocus: true, class: "form-control" %></div>
	 </div>

	 <div class="row mt-5">
	    <div class="col-3 offset-3">
	      <%= f.submit "企業情報を登録する", class: "btn btn-success btn-block" %>
	    </div>
	 </div>

</div>
<% end %>

app/views/users/companies/show.html.erb
<div class="container">
	<%= render "users/top/list" %>

	<div class="row mt-5">
		<div class="col-5">
			<canvas class="text-center" id="myRaderChart" width="200" height="120"></canvas><br>
			<div class="text-center h4">総合評価</div>
			<div class="text-center" id="star-rate"></div>
			<script>
		        	$('#star-rate').raty({
               	  	size: 50,
                  	starOff:  '<%= asset_path("原画star-off.png") %>',
                  	starOn : '<%= asset_path("原画star-on.png") %>',
                  	starHalf: '<%= asset_path("原画star-half.png") %>',
                  	half: true,
                  	readOnly: true,
                  	score: <%= @company.evaluations.count == 0 ? 0 : @company.evaluations.pluck(:average).sum / @company.evaluations.count %>,
                	});
				var ctx = document.getElementById("myRaderChart");
				var myChart = new Chart(ctx, {
				  type: 'radar',
				  data: {
				    labels: ["労働時間の満足度", "仕事のやりがい", "社員同士のコミュニケーション", "休日数の満足度", "給与の満足度", "社員の成長環境"],
				    datasets: [{
				      backgroundColor: "rgba(17,77,217,0.2",
				      borderColor: "rgba(17,77,217,0.5)",
				      data: [<%= @company.evaluations.count == 0 ? 0 : @company.evaluations.pluck(:working_time).sum / @company.evaluations.count %>,
				       		 <%= @company.evaluations.count == 0 ? 0 : @company.evaluations.pluck(:rewarding).sum / @company.evaluations.count %>,
				       		 <%= @company.evaluations.count == 0 ? 0 : @company.evaluations.pluck(:communication).sum / @company.evaluations.count %>,
				       		 <%= @company.evaluations.count == 0 ? 0 : @company.evaluations.pluck(:holiday).sum / @company.evaluations.count %>,
				       		 <%= @company.evaluations.count == 0 ? 0 : @company.evaluations.pluck(:salary).sum / @company.evaluations.count %>,
				       		 <%= @company.evaluations.count == 0 ? 0 : @company.evaluations.pluck(:growth_environment).sum / @company.evaluations.count %>]
				    }]
				  },
				  options: {
				  	legend: {
				  		display: false
				  	},
				  	scale: {
				  		ticks: {
				  			max: 5,
				  			min: 0,
				  			stepSize: 1
				  		}
				  	}
				  }
				});
			</script>
		</div>
		<div class="col-7">
			<table class="table table-bordered mt-3">
				<tr>
					<th class="table-primary">会社名</th>
					<td><%= @company.company_name %></td>
				</tr>
				<tr>
					<th class="table-primary">本社所在地</th>
					<td><%= @company.main_office %></td>
				</tr>
				<tr>
					<th class="table-primary">代表者</th>
					<td><%= @company.ceo %></td>
				</tr>
				<tr>
					<th class="table-primary">従業員数</th>
					<td><%= @company.employee_number %>人</td>
				</tr>
				<tr>
					<th class="table-primary">設立年月</th>
					<td><%= @company.foundation_date.strftime("%Y年%m月") %></td>
				</tr>
				<tr>
					<th class="table-primary">上場区分</th>
					<td><%= @company.is_listing %></td>
				</tr>
				<tr>
					<th class="table-primary">HP</th>
					<td><%= @company.hp %></td>
				</tr>
			</table>
		</div>
	</div>

	<div class="row mt-5">
		<div class="col-auto mr-auto h3">クチコミ一覧</div>
		<div class="col-auto"><%= link_to "口コミを書く", new_users_company_evaluation_path(@company), class: "btn btn-success" %></div>
	</div>

	<div class="row mt-1">
		<div class="col">
			<table class="table">
				<% @company.evaluations.each do |evaluation| %>
					<tr>
						<td class="align-middle border-bottom" width="400"><%= evaluation.generation %>／<%= evaluation.gender %>／<%= evaluation.employment_type %>／<%= evaluation.enrollment_period %>／<%= evaluation.is_enrollment %><br><div id="star-rate-<%= evaluation.id %>"></div></td>
						<td class="align-middle border-bottom"><span class="d-inline-block text-truncate" style="max-width: 500px;"><%= evaluation.review %></span></td>
						<td class="align-middle border-bottom" width="150"><%= link_to "詳細を見る", users_company_evaluation_path(@company,evaluation) %></td>
					</tr>
					<script>
		        	$('#star-rate-<%= evaluation.id %>').raty({
               	  	size: 50,
                  	starOff: '<%= asset_path("原画star-off.png") %>',
                  	starOn : '<%= asset_path("原画star-on.png") %>',
                  	starHalf: '<%= asset_path("原画star-half.png") %>',
                  	half: true,
                  	readOnly: true,
                  	score: <%= evaluation.average %>,
                	});
					</script>
				<% end %>
			</table>
		</div>
	</div>

</div>